### ISSUE TITLE
bin"file_name"??

### ISSUE THREAD

**Issue by Maeve-D** [Yuseung-Na/pcd2bin#1]
i want to transfer .pcd format to .bin format
i name .bin myself??
eg: 1.bin??

**Comment by Yuseung-Na** [comment]
Hello,
Check line 87 of source code.

The naming rule is {"file_name"}_{"sequence_number"}.bin

So, if you specify a name like "example", then it automatically outputs like "example_00001.bin, example_00002.bin, ..."
