### ISSUE TITLE
module 'pypcd' has no attribute 'PointCloud'

### ISSUE THREAD

**Issue by eiffelbastin** [Yuseung-Na/pcd2bin#5]
hey buddy I'm getting this trackback while running the code... pls see if u can help

thanks in advance :)

`Finish to load point clouds!
Finish to generate csv meta file
Converting Start!
  0%|                                                                          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "pcd2bin.py", line 112, in <module>
    main()
  File "pcd2bin.py", line 84, in main
    pc = pypcd.PointCloud.from_path(pcd_file)
AttributeError: module 'pypcd' has no attribute 'PointCloud'`

**Comment by Yuseung-Na** [comment]
I've checked that.
If the python version is 3.x, pypcd from pip install is not working.

**Comment by eiffelbastin** [comment]
whats the solution u suggest??
run with a lower version of py ?  Or some otherway to install pypcd instead of pip?

**Comment by Yuseung-Na** [comment]
Currently I'm trying to solve this issue with Python 3.x.
You have to install pypcd from github https://github.com/dimatura/pypcd

**Comment by laiyingxin2** [comment]
from pypcd import pypcd work for me

**Comment by Yuseung-Na** [comment]
@laiyingxin2 Thanks alot!

**Comment by eiffelbastin** [comment]
> from pypcd import pypcd work for me

which version of python were you using?

**Comment by laiyingxin2** [comment]
I use version python 3.7

**Comment by eiffelbastin** [comment]
`C:\Users\91828\Downloads\folder>python pcd2bin.py --pcd_path=C:\Users\91828\Downloads\folder\pcd --bin_path=C:\Users\91828\Downloads\folder\bin --file_name=test123
Finish to load point clouds!
Finish to generate csv meta file
Converting Start!
Traceback (most recent call last):
  File "C:\Users\91828\Downloads\folder\pcd2bin.py", line 112, in <module>
    main()
  File "C:\Users\91828\Downloads\folder\pcd2bin.py", line 82, in main
    for pcd_file in tqdm(pcd_files):
TypeError: 'module' object is not callable`



any idea??

**Comment by eiffelbastin** [comment]
![image](https://user-images.githubusercontent.com/83037376/160803990-bc243df5-7c23-4bb8-a047-629a7348fa30.png)


any idea

**Comment by eiffelbastin** [comment]
![Screenshot 2022-03-30 152225](https://user-images.githubusercontent.com/83037376/160804207-733bbdfe-e960-4f7e-9126-e55ad78a1ef2.jpg)


any idea???

**Comment by ghanim-mukhtar** [comment]
I am using python3 version 3.9.12 and `from pypcd import pypcd` gave me an error: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ghanim/anaconda3/lib/python3.9/site-packages/pypcd/pypcd.py", line 15, in <module>
    import cStringIO as sio
ModuleNotFoundError: No module named 'cStringIO'
``` 
and apparently the cStringIO is replaced for later versions of python3 by StringIO in module io. So a work around is needed here.

**Comment by scb-vs5** [comment]
don't use pypcd, and change to open3d! pypcd has too many problems!
